In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model
from sklearn.linear_model import LinearRegression

In [4]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
df=pd.read_excel("77countries.xlsx")
#df=df[0:30]
#State=df.State.unique()
#df_last_date=df[df['date']=="2020-09-03"]

In [6]:
df

,continent,location,total_deaths,R0,total_cases,new_cases,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,hospital_beds_per_thousand,life_expectancy
0,North America,United States,185744,2.465409,6114406,38754,331002647,35.608,38.3,15.413,9.732,54225.446,1.2,151.089,10.79,19.1,24.6,2.77,78.86
1,South America,Brazil,123780,2.000668,3997865,46934,212559409,25.040,33.5,8.552,5.060,14103.452,3.4,177.961,8.11,10.1,17.9,2.20,75.88
2,Asia,India,67376,1.731947,3853406,83883,1380004385,450.419,28.2,5.989,3.414,6426.674,21.2,282.280,10.39,1.9,20.6,0.53,69.66
3,North America,Mexico,65816,1.800513,610957,4921,128932753,66.444,29.3,6.857,4.321,17336.469,2.5,152.783,13.06,6.9,21.4,1.38,75.05
4,Europe,United Kingdom,41514,2.042228,338676,1508,67886004,272.898,40.8,18.517,12.527,39753.244,0.2,122.137,4.28,20.0,24.7,2.54,81.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Europe,Albania,296,2.268620,9728,122,2877800,104.871,38.0,13.188,8.643,11803.431,1.1,304.195,10.08,7.1,51.2,2.89,78.57
73,Africa,Zambia,292,1.908191,12415,34,18383956,22.995,17.7,2.480,1.542,3689.251,57.5,234.499,3.94,3.1,24.7,2.00,63.89
74,Africa,Senegal,287,1.453346,13743,75,16743930,82.328,18.7,3.008,1.796,2470.580,38.0,241.219,2.42,0.4,16.6,NaN,67.94
75,Africa,Ghana,276,2.037094,44658,198,31072945,126.719,21.1,3.385,1.948,4227.630,12.0,298.245,4.97,0.3,7.7,0.90,64.07
76,Europe,Greece,273,3.141513,10757,233,10423056,83.479,45.3,20.396,14.524,24574.382,1.5,175.695,4.55,35.3,52.0,4.21,82.24

In [7]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   continent                   77 non-null     object
 1   location                    77 non-null     object
 2   total_deaths                77 non-null     int64
 3   R0                          77 non-null     float64
 4   total_cases                 77 non-null     int64
 5   new_cases                   77 non-null     int64
 6   population                  77 non-null     int64
 7   population_density          77 non-null     float64
 8   median_age                  77 non-null     float64
 9   aged_65_older               77 non-null     float64
 10  aged_70_older               76 non-null     float64
 11  gdp_per_capita              77 non-null     float64
 12  extreme_poverty             58 non-null     float64
 13  cardiovasc_death_rate       77 non-null     float64
 14  diabetes_prevalence         77 non-null     float64
 15  female_smokers              72 non-null     float64
 16  male_smokers                70 non-null     float64
 17  hospital_beds_per_thousand  75 non-null     float64
 18  life_expectancy             77 non-null     float64
dtypes: float64(13), int64(4), object(2)
memory usage: 11.6+ KB
None

In [131]:
#Filling missing values

In [8]:
l=df.columns
l

Index(['continent', 'location', 'total_deaths', 'R0', 'total_cases',
       'new_cases', 'population', 'population_density', 'median_age',
       'aged_65_older', 'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'hospital_beds_per_thousand', 'life_expectancy'],
      dtype='object')

In [9]:
df.dropna(inplace=True)

In [10]:
df

,continent,location,total_deaths,R0,total_cases,new_cases,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,hospital_beds_per_thousand,life_expectancy
0,North America,United States,185744,2.465409,6114406,38754,331002647,35.608,38.3,15.413,9.732,54225.446,1.2,151.089,10.79,19.1,24.6,2.770,78.86
1,South America,Brazil,123780,2.000668,3997865,46934,212559409,25.040,33.5,8.552,5.060,14103.452,3.4,177.961,8.11,10.1,17.9,2.200,75.88
2,Asia,India,67376,1.731947,3853406,83883,1380004385,450.419,28.2,5.989,3.414,6426.674,21.2,282.280,10.39,1.9,20.6,0.530,69.66
3,North America,Mexico,65816,1.800513,610957,4921,128932753,66.444,29.3,6.857,4.321,17336.469,2.5,152.783,13.06,6.9,21.4,1.380,75.05
4,Europe,United Kingdom,41514,2.042228,338676,1508,67886004,272.898,40.8,18.517,12.527,39753.244,0.2,122.137,4.28,20.0,24.7,2.540,81.32
5,Europe,Italy,35497,4.184995,271515,1326,60461828,205.859,47.9,23.021,16.240,35220.084,2.0,113.151,4.78,19.8,27.8,3.180,83.51
8,Asia,Iran,21797,1.532991,378752,1858,83992953,49.831,32.4,5.440,3.182,19082.620,0.2,270.308,9.59,0.8,21.1,1.500,76.68
9,South America,Colombia,20348,1.991294,633339,9270,50882884,44.223,32.2,7.646,4.312,13254.949,4.5,124.240,7.44,4.7,13.5,1.710,77.29
10,Europe,Russia,17414,2.716937,1005000,4952,145934460,8.823,39.6,14.178,9.393,24765.954,0.1,431.297,6.18,23.4,58.3,8.050,72.58
11,Africa,South Africa,14389,1.761732,630595,2336,59308690,46.754,27.3,5.344,3.053,12294.876,18.9,200.380,5.52,8.1,33.2,2.320,64.13
12,South America,Chile,11344,2.250374,414739,1594,19116209,24.282,35.4,11.087,6.938,22767.037,1.3,127.993,8.46,34.2,41.5,2.110,80.18
13,Europe,Belgium,9898,3.598751,85817,0,11589616,375.564,41.8,18.571,12.849,42658.576,0.2,114.898,4.29,25.1,31.4,5.640,81.63
15,North America,Canada,9135,2.764913,129923,498,37742157,4.037,41.4,16.984,10.797,44017.591,0.5,105.599,7.37,12.0,16.6,2.500,82.43
16,South America,Argentina,8971,2.114039,428226,10504,45195777,16.177,31.9,11.198,7.441,18933.907,0.6,191.032,5.50,16.2,27.7,5.000,76.67
17,Asia,Indonesia,7616,2.023743,180646,3075,273523621,145.725,29.3,5.319,3.053,11188.744,5.7,342.864,6.32,2.8,76.1,1.040,71.72
19,South America,Ecuador,6619,1.872841,115457,1148,17643060,66.939,28.1,7.104,4.458,10581.936,3.6,140.448,5.55,2.0,12.3,1.500,77.01
20,Asia,Turkey,6462,1.711242,273301,1596,84339067,104.914,31.6,8.153,5.061,25129.341,0.2,171.285,12.13,14.1,41.1,2.810,77.69
21,Asia,Pakistan,6328,1.362303,297014,424,220892331,255.573,23.5,4.495,2.780,5034.708,4.0,423.031,8.35,2.8,36.7,0.600,67.27
23,Europe,Sweden,5820,3.206547,84532,0,10099270,24.718,41.0,19.985,13.433,46949.283,0.5,133.982,4.79,18.8,18.9,2.220,82.80
24,Africa,Egypt,5461,1.434267,99280,165,102334403,97.999,25.3,5.159,2.891,10550.206,1.3,525.432,17.31,0.2,50.1,1.600,71.99
26,Asia,China,4727,2.436220,89953,19,1439323774,147.674,38.7,10.641,5.929,15308.712,0.7,261.899,9.74,1.9,48.4,4.340,76.91
27,Asia,Bangladesh,4351,1.618151,317528,2582,164689383,1265.036,27.5,5.098,3.262,3523.984,14.8,298.003,8.38,1.0,44.7,0.800,72.59
29,Europe,Romania,3721,2.701301,89891,1298,19237682,85.129,43.0,17.850,11.690,23313.199,5.7,370.946,9.74,22.9,37.1,6.892,76.05
32,Europe,Ukraine,2656,3.038230,125789,2486,43733759,77.390,41.4,16.462,11.133,7894.393,0.1,539.849,7.11,13.5,47.4,8.800,72.06
34,North America,Panama,2030,1.823209,94084,532,4314768,55.133,29.7,7.918,5.030,22267.037,2.2,128.346,8.33,2.4,9.9,2.300,78.51
36,Asia,Kazakhstan,1889,2.260230,132354,659,18776707,6.681,30.6,6.991,4.625,24055.588,0.1,466.792,7.11,7.0,43.1,6.700,73.60
37,Europe,Portugal,1827,3.112976,58633,390,10196707,112.371,46.2,21.502,14.924,27936.896,0.5,127.842,9.85,16.3,30.0,3.390,82.05
38,Europe,Ireland,1777,2.265882,29114,89,4937796,69.874,38.7,13.928,8.678,67335.293,0.2,126.459,3.28,23.0,25.7,2.960,82.30
39,North America,Dominican Republic,1765,1.846620,95627,648,10847904,222.873,27.6,6.981,4.419,14600.861,1.6,266.653,8.20,8.5,19.1,1.600,74.08
41,Africa,Algeria,1525,1.359804,45158,325,43851043,17.348,29.1,6.211,3.857,13913.839,0.5,278.364,6.73,0.7,30.4,1.900,76.88
43,Africa,Morocco,1216,1.656326,65453,1672,36910558,80.080,29.6,6.769,4.209,7485.013,1.0,419.146,7.14,0.8,47.1,1.100,76.68
44,Asia,Kyrgyzstan,1059,1.737408,44135,99,6524191,32.333,26.3,4.489,2.882,3393.474,1.4,436.362,7.11,3.6,50.5,4.500,71.45
46,Asia,Israel,969,2.094296,122539,3274,8655541,402.606,30.6,11.733,7.359,33132.320,0.5,93.320,6.74,15.4,35.4,2.990,82.97
47,Asia,Armenia,884,2.455895,44075,197,2963234,102.931,35.7,11.232,7.571,8787.580,1.8,341.010,7.11,1.5,52.1,4.200,75.09
48,Africa,Ethiopia,846,2.061205,54409,1105,114963583,104.957,19.8,3.526,2.063,1729.927,26.7,182.634,7.47,0.4,8.5,0.300,66.60
49,North America,El Salvador,739,1.807100,25904,0,6486201,307.811,27.6,8.273,5.417,7292.458,2.2,167.295,8.87,2.5,18.8,1.300,73.32
50,Europe,Austria,734,3.014221,28183,442,9006400,106.749,44.4,19.202,13.748,45436.686,0.7,145.183,6.35,28.4,30.9,7.370,81.54
54,Oceania,Australia,663,2.555908,25923,104,25499881,3.202,37.9,15.504,10.129,44648.710,0.5,107.791,5.07,13.0,16.5,3.840,83.44
55,Europe,Bulgaria,642,3.516514,16454,188,6948445,65.180,44.7,20.801,13.272,18563.307,1.5,424.688,5.81,30.1,44.4,7.454,75.05
56,Europe,Bosnia and Herzegovina,627,2.773516,20517,283,3280815,68.496,42.5,16.569,10.711,11713.895,0.2,329.635,10.08,30.2,47.7,3.500,77.40
57,Europe,Denmark,626,3.178221,17195,111,5792203,136.520,42.3,19.677,12.325,46682.515,0.2,114.767,6.41,19.3,18.8,2.500,80.90
58,Europe,Hungary,619,3.091244,6622,365,9660350,108.043,43.4,18.577,11.976,26777.561,0.5,278.296,7.55,26.8,34.8,7.020,76.88
59,Africa,Kenya,577,1.662634,34493,178,53771300,87.324,20.0,2.686,1.528,2993.028,36.8,218.637,2.92,1.2,20.4,1.400,66.70
60,Asia,Yemen,571,1.062837,1976,14,29825968,53.508,20.3,2.922,1.583,1479.147,18.8,495.003,5.35,7.6,29.2,0.700,66.12
63,North America,Costa Rica,453,1.959368,43305,1121,5094114,96.079,33.6,9.468,5.694,15524.995,1.3,137.973,8.78,6.4,17.4,1.130,80.28
68,South America,Paraguay,358,1.888903,19138,800,7132530,17.144,26.5,6.378,3.833,8827.010,1.7,199.128,8.27,5.0,21.6,1.300,74.25
70,Asia,South Korea,329,2.660926,20644,195,51269183,527.967,43.4,13.914,8.622,35938.374,0.2,85.998,6.80,6.2,40.9,12.270,83.03
72,Europe,Albania,296,2.268620,9728,122,2877800,104.871,38.0,13.188,8.643,11803.431,1.1,304.195,10.08,7.1,51.2,2.890,78.57
73,Africa,Zambia,292,1.908191,12415,34,18383956,22.995,17.7,2.480,1.542,3689.251,57.5,234.499,3.94,3.1,24.7,2.000,63.89
75,Africa,Ghana,276,2.037094,44658,198,31072945,126.719,21.1,3.385,1.948,4227.630,12.0,298.245,4.97,0.3,7.7,0.900,64.07
76,Europe,Greece,273,3.141513,10757,233,10423056,83.479,45.3,20.396,14.524,24574.382,1.5,175.695,4.55,35.3,52.0,4.210,82.24

In [11]:
df_numerical=df.iloc[:,2:]

In [12]:
df_numerical.shape

(51, 17)

### Using only Elasticnet regression

In [13]:
df_final=df_numerical
y_train_reg = df_final['total_deaths']
x_train_reg = df_final.drop('total_deaths',axis=1)
x_test=x_train_reg.iloc[2:3,:]

In [56]:
from sklearn.linear_model import HuberRegressor
from sklearn import linear_model
ridge_reg = linear_model.Ridge(alpha=.5)
ridge_reg.fit(x_train_reg,y_train_reg)

Ridge(alpha=0.5)

In [57]:
ridge_reg.predict(x_test)

array([73006.9691871])

In [53]:
lm=LinearRegression()

In [54]:
lm.fit(x_train_reg,y_train_reg)

LinearRegression()

In [55]:
lm.predict(x_test)

array([73101.45170621])

In [99]:
coeff=en_reg.coef_

In [100]:
intercept=en_reg.intercept_

In [14]:
def dictionary(df,location):
    df_location=df[df['location']==location]
    df_location=df_location.iloc[:,3:]
    df_location_dict=df_location.to_dict('records')
    
    return df_location_dict

In [15]:
location="India"
df_location_dict=dictionary(df,location)

In [16]:
death=inter
k=0
for i in df_location_dict[0].values():
    death=death+(i*coeff[k])
    k=k+1

NameError: name 'inter' is not defined

In [105]:
death

71241.1945330599

In [17]:
from sklearn.linear_model import ElasticNet

In [59]:
lasso_reg = linear_model.Lasso(alpha=0.1)
lasso_reg.fit(x_train_reg,y_train_reg)

lasso_reg.predict(x_test)

array([73098.86254388])

In [18]:
en_reg = ElasticNet(random_state=0)
en_reg.fit(x_train_reg,y_train_reg)

en_reg.predict(x_test)

array([72393.51184758])

In [94]:
en_reg.coef_[0]

-26.200453728402575

In [89]:
en_reg.intercept_

-6924.314960388718

In [90]:
en_reg.n_features_in_

16

In [91]:
x_train_reg.columns

Index(['R0', 'total_cases', 'new_cases', 'population', 'population_density',
       'median_age', 'aged_65_older', 'aged_70_older', 'gdp_per_capita',
       'extreme_poverty', 'cardiovasc_death_rate', 'diabetes_prevalence',
       'female_smokers', 'male_smokers', 'hospital_beds_per_thousand',
       'life_expectancy'],
      dtype='object')

In [93]:
x_train_reg.iloc[2:3,:]

,R0,total_cases,new_cases,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,hospital_beds_per_thousand,life_expectancy
2,1.731947,3853406,83883,1380004385,450.419,28.2,5.989,3.414,6426.674,21.2,282.28,10.39,1.9,20.6,0.53,69.66

In [19]:
R0=1.731947
total_cases=3853406
new_cases=83883
population=1380004385
population_density=450.419
median_age=28.2
aged_65_older=5.989
aged_70_older=3.414
gdp_per_capita=6426.674
extreme_poverty=21.2
cardiovasc_death_rate=282.28
diabetes_prevalence=10.39
female_smokers=1.9
male_smokers=20.6
hospital_beds_per_thousand=0.53
life_expectancy=69.66

In [20]:
intercept=en_reg.intercept_
R0_coef=en_reg.coef_[0]
total_cases_coef=en_reg.coef_[1]
new_cases_coef=en_reg.coef_[2]
population_coef=en_reg.coef_[3]
population_density_coef=en_reg.coef_[4]
median_age_coef=en_reg.coef_[5]
aged_65_older_coef=en_reg.coef_[6]
aged_70_older_coef=en_reg.coef_[7]
gdp_per_capita_coef=en_reg.coef_[8]
extreme_poverty_coef=en_reg.coef_[9]
cardiovasc_death_rate_coef=en_reg.coef_[10]
diabetes_prevalence_coef=en_reg.coef_[11]
female_smokers_coef=en_reg.coef_[12]
male_smokers_coef=en_reg.coef_[13]
hospital_beds_per_thousand_coef=en_reg.coef_[14]
life_expectancy_coef=en_reg.coef_[15]

In [115]:
diabetes_prevalence_coef
hospital_beds_per_thousand_coef
median_age_coef
total_cases_coef
aged_70_older_coef
extreme_poverty_coef
female_smokers_coef
male_smokers_coef
R0_coef

410.930002769215

In [29]:
male_smokers_coef

-89.79111260507828

In [22]:
death=intercept+(R0_coef*R0)+(total_cases_coef*total_cases)+(new_cases_coef*new_cases)+(population_coef*population)+(population_density_coef*population_density)+(median_age_coef*median_age)+(aged_65_older_coef*aged_65_older)+(aged_70_older_coef*aged_70_older)+(gdp_per_capita_coef*gdp_per_capita)+(extreme_poverty_coef*extreme_poverty)+(cardiovasc_death_rate_coef*cardiovasc_death_rate)+(diabetes_prevalence_coef*diabetes_prevalence)+(female_smokers_coef*female_smokers)+(male_smokers_coef*male_smokers)+(hospital_beds_per_thousand_coef*hospital_beds_per_thousand)+(life_expectancy_coef*life_expectancy)

In [23]:
death

72393.51183923168

In [109]:
en_reg.coef_

array([-2.62004537e+01,  3.60584668e-02, -8.06213173e-01, -2.18981243e-06,
       -2.99663967e+00,  4.10930003e+02, -3.72163973e+02,  7.08752062e+02,
       -7.54569970e-02, -1.72813896e+01, -1.30774630e+01,  3.76619160e+02,
       -1.49054329e+02, -8.97911126e+01, -7.58936357e+02,  5.45567485e+01])